In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [7]:
f= np.array([1,2,3,4,5], ndmin=2, dtype = complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]])

In [8]:
np.dtype(np.int32) 

dtype('int32')

In [9]:
np.dtype(np.int32)

dtype('int32')

In [10]:
np.dtype('i4')

dtype('int32')

In [11]:
a= np.array([(10,), (20,), (30,)])
a

array([[10],
       [20],
       [30]])

In [13]:
a= np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [14]:
a.shape = (3,2)

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b = a.reshape(2,3)

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
a.ndim

1

In [21]:
a.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [23]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
x.itemsize

1

In [24]:
x = np.empty([3,2], dtype=float)

In [31]:
x

array([[4.67296746e-307, 1.69121096e-306, 1.78020848e-306,
        6.23054972e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [30]:
y = np.empty([4,4], dtype=float)
y

array([[4.67296746e-307, 1.69121096e-306, 1.78020848e-306,
        6.23054972e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [38]:
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

In [43]:
x = [(1,2,3),(4,5)] 
d = np.asarray(x)
d

array([(1, 2, 3), (4, 5)], dtype=object)

In [48]:
list = range(5) 
print(list)

range(0, 5)


In [50]:
it = iter(list)
y = np.fromiter(it, dtype=float)

In [51]:
y

array([0., 1., 2., 3., 4.])

In [53]:
t = np.arange(2,20,2, dtype = float)
t

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [54]:
d= np.arange(10,20,2)
d

array([10, 12, 14, 16, 18])

In [56]:
h = np.linspace(2,10,5)
h

array([ 2.,  4.,  6.,  8., 10.])

In [57]:
d = np.arange(10)
s = slice(2,10,1)

In [59]:
d[s]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
e=np.arange(10)
x = e[2:2]
x

array([], dtype=int32)

In [65]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [68]:
 a[...,1:] 

array([[2, 3],
       [4, 5],
       [5, 6]])

In [69]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

In [70]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
a*b

array([ 10,  40,  90, 160])

In [71]:
a+b

array([11, 22, 33, 44])

In [72]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
y

array([1, 4, 5])

In [74]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [76]:
y = a.reshape(2,2)

In [77]:
y

array([[2, 4],
       [6, 8]])

In [81]:
for x in np.nditer(y):
    print(x)

2
4
6
8


In [82]:
y.T

array([[2, 6],
       [4, 8]])

In [84]:
a  = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
a.flat[5]

5

In [89]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
d= np.concatenate((a,b),axis = 1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [94]:
np.stack((a,b), 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [98]:
np.char.add(['hello '], ['anjali'])

array(['hello anjali'], dtype='<U12')

In [99]:
np.char.add(['hi', 'hello'], ['anjali', 'gaurav'])

array(['hianjali', 'hellogaurav'], dtype='<U11')

In [102]:
np.char.multiply('hello', 3)

array('hellohellohello', dtype='<U15')

In [103]:
np.char.center('hello', 20, fillchar='*')

array('*******hello********', dtype='<U20')

In [104]:
np.char.capitalize('hello')

array('Hello', dtype='<U5')

In [106]:
np.char.title('how are you')

array('How Are You', dtype='<U11')

In [108]:
np.char.split('helloji, how aare you', sep=',')

array(list(['helloji', ' how aare you']), dtype=object)

In [109]:
np.char.replace('he is good', 'is', 'was')

array('he was good', dtype='<U11')

In [110]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [112]:
np.sin(a*np.pi/100)

array([0.30901699, 0.58778525, 0.80901699, 0.95105652, 1.        ])

In [113]:
a = np.array([0,30,45,60,90]) 
a

array([ 0, 30, 45, 60, 90])

In [114]:
sin = np.sin(a*np.pi/180) 
sin

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [119]:
inv = np.arcsin(sin) 
np.degrees(inv)

array([ 0., 30., 45., 60., 90.])

In [120]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 
b = np.array([10,10,10]) 
np.add(a,b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [121]:
np.subtract(a,b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [122]:
np.multiply(a,b)

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

In [124]:
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [125]:
np.power(a,2)

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [126]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [127]:
np.reciprocal(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

In [128]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [132]:
np.amin(a,0)

array([2, 4, 3])

In [133]:
np.ptp(a,0)

array([6, 3, 6])

In [134]:
np.percentile(a,50,axis=0)

array([3., 4., 5.])

In [135]:
np.median(a, axis= 0)

array([3., 4., 5.])

In [136]:
np.std([1,2,3,4])

1.118033988749895

In [137]:
np.var([1,2,3,4])

1.25

In [138]:
a = np.array([[3,7],[9,1]]) 
a

array([[3, 7],
       [9, 1]])

In [141]:
np.sort(a,axis=0)

array([[3, 1],
       [9, 7]])

In [142]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [143]:
np.vdot(a,b)

130

In [144]:
import numpy as np 
a = np.array([[1,2], [3,4]]) 
b = np.array([[11, 12], [13, 14]]) 

np.inner(a,b)

array([[35, 41],
       [81, 95]])

In [145]:
a = np.array([[1,2], [3,4]])
np.linalg.det(a)

-2.0000000000000004